/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio.pkg4.modulo.pkg2.clase.pkg6.parte.pkg3;

import java.util.TreeSet;

/**
 *
 * @author Jorge Santiago
 */
public class Supermercado extends javax.swing.JFrame {
public static TreeSet<Producto> listaProducto= new TreeSet<>(); // Es un TreeSet de Objeto Producto que crea una lista que ordena
                                                               // los Productos creados de manera natural


    /**
     * Creates new form Supermercado
     */
    public Supermercado() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAdmin = new javax.swing.JMenu();
        jMProductos = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenu();
        jMRubro = new javax.swing.JMenuItem();
        jMNombre = new javax.swing.JMenuItem();
        jMPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDEscritorio.setName(""); // NOI18N
        jDEscritorio.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMAdmin.setText("Administracion");

        jMProductos.setText("Productos");
        jMProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProductosActionPerformed(evt);
            }
        });
        jMAdmin.add(jMProductos);

        jMenuBar1.add(jMAdmin);

        jMConsulta.setText("Consulta");

        jMRubro.setText("Por Rubro");
        jMRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRubroActionPerformed(evt);
            }
        });
        jMConsulta.add(jMRubro);

        jMNombre.setText("Por Nombre");
        jMNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNombreActionPerformed(evt);
            }
        });
        jMConsulta.add(jMNombre);

        jMPrecio.setText("Por Precio");
        jMPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPrecioActionPerformed(evt);
            }
        });
        jMConsulta.add(jMPrecio);

        jMenuBar1.add(jMConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNombreActionPerformed
                                                    // con eso se crea el voto para ingresar a "por nombre"
                                                    // y se la vincula con el JMInternalFrame
                                                    // y posteriormente se hace aparecer la pantalla nueva con moveToFront
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        PorNombre xnombre= new PorNombre();
        xnombre.setVisible(true);
        jDEscritorio.add(xnombre);
        jDEscritorio.moveToFront(xnombre);
        
    }//GEN-LAST:event_jMNombreActionPerformed

    private void jMRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRubroActionPerformed
                                                    // con eso se crea el voto para ingresar al menu de "por rubo"
                                                    // y se la vincula con el JMInternalFrame por rubro
                                                    // y posteriormente se hace aparecer la pantalla nueva con moveToFront
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        PorRubro xrubro= new PorRubro();
        xrubro.setVisible(true);
        jDEscritorio.add(xrubro);
        jDEscritorio.moveToFront(xrubro);
        
    }//GEN-LAST:event_jMRubroActionPerformed

    private void jMPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPrecioActionPerformed
                                                    // con eso se crea el voto para ingresar al menu de "por rubo"
                                                    // y se la vincula con el JMInternalFrame por rubro
                                                    // y posteriormente se hace aparecer la pantalla nueva con moveToFront
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        PorPrecio xprecio= new PorPrecio();
        xprecio.setVisible(true);
        jDEscritorio.add(xprecio);
        jDEscritorio.moveToFront(xprecio);
        
    }//GEN-LAST:event_jMPrecioActionPerformed

    private void jMProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProductosActionPerformed
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        GestionProductos menu= new GestionProductos();    // poniendo el nombre de GestioProductos la vinculo con el InterFrame
        menu.setVisible(true);                            // con la variable menu llamo a ese Objeto 
        jDEscritorio.add(menu);
        jDEscritorio.moveToFront(menu);
        
    }//GEN-LAST:event_jMProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenu jMAdmin;
    private javax.swing.JMenu jMConsulta;
    private javax.swing.JMenuItem jMNombre;
    private javax.swing.JMenuItem jMPrecio;
    private javax.swing.JMenuItem jMProductos;
    private javax.swing.JMenuItem jMRubro;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
        listaProducto.add(new Producto (020,"Vacio",2560, "1 kg de Vacio de Ternera",5,Categorias.CARNICERIA));
        listaProducto.add(new Producto(014,"Queso",700, "1 Kg de Queso Roquefort", 10, Categorias.FIAMBRERIA));
        listaProducto.add(new Producto(863,"Galletas", 450, "Galletas Dulces x 350gr", 6, Categorias.ALIMENTOS));
        listaProducto.add(new Producto(052,"Fernet", 3030, "Fernet Branca x 1Lt", 9, Categorias.BEBIDAS));
        listaProducto.add(new Producto(010, "Lavandina", 800, "Lavandina Ala", 21, Categorias.LIMPIEZA));
    }

}
